name: CI Pipeline

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest flake8 black

    - name: Debug Git
      run: |
        git status
        git log -1

    - name: Lint
      run: flake8 .

    - name: Format check
      run: black .

    - name: Tests
      run: pytest