name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          # On peut garder 'user' et 'bdd_projet_certif' en clair car ce ne sont pas des secrets,
          # mais on sécurise le mot de passe critique.
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: bdd_projet_certif
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio "httpx[http2]"

    - name: Debug Git
      run: |
        git status
        git log -1

    #- name: Lint
    #  run: flake8 . --ignore=E501

    #- name: Format check
     # run: black --check .
    - name: Initialize Database Schema
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        psql -h localhost -U ${{ secrets.DB_USER }} -d bdd_projet_certif -f init.sql

    - name: Tests
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: bdd_projet_certif
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        MLFLOW_TRACKING_URI: http://localhost:5000
      run: |
        pytest -o pythonpath=. tests/